#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        	0
bspc config border_radius		      10
bspc config window_gap          	30
bspc config pointer_modifier		  super
bspc config pointer_action1		    move
bspc config pointer_action3		    resize_side
bspc config split_ratio         	0.5
bspc config top_padding 		      -10
bspc config bottom_padding		    0
bspc config left_padding		      0
bspc config right_padding		      40
bspc config normal_border_color 	'#0088ff'
bspc config active_border_color 	'#0088ff'
bspc config focused_border_color 	'#00ffff'
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer	true
bspc rule -a '*:ferdi' state=floating sticky=on
